@FrasesRandomAPI_HostAddress = http://localhost:5151

GET {{FrasesRandomAPI_HostAddress}}/frases
Accept: application/json

###

GET {{FrasesRandomAPI_HostAddress}}/frases/{id}
Accept: application/json

###

POST {{FrasesRandomAPI_HostAddress}}/frases
Content-Type: application/json

{
    "texto": "Nueva frase",
    "autor": "Autor"
}

###

PUT {{FrasesRandomAPI_HostAddress}}/frases/{id}
Content-Type: application/json

{
    "texto": "Frase actualizada",
    "autor": "Autor actualizado"
}

###

DELETE {{FrasesRandomAPI_HostAddress}}/frases/{id}

###
